// High-fidelity Mock Data for CivicPulse AI Platform
// Compliant with Pydantic & MongoDB Schemas

import { Category, Status, Priority, UserRole, DepartmentsList, ResidentBenefitsCatalog, VisitorBenefitsCatalog } from "../utils/constants";

export const initialMockUsers = [
  {
    id: "usr_official_01",
    name: "Officer Sarah Chen",
    email: "s.chen@civicpulse.gov",
    phone: "+1 (555) 912-3841",
    role: UserRole.CIVIC_OFFICIAL,
    department: "Roads & Infrastructure",
    residentStatus: "Civil Service Personnel",
    city: "Metropolitan District",
    profilePhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80",
    civicPoints: 850,
    civicLevel: "Civic Leader",
    trustScore: 99,
    memberSince: "2024-01-15",
    reportsSubmitted: 0,
    reportsValidated: 142,
    issuesResolved: 98,
    impactLevel: "SUPERVISOR",
  },
  {
    id: "usr_resident_01",
    name: "Marcus Vance",
    email: "marcus.vance@gmail.com",
    phone: "+1 (555) 342-8819",
    role: UserRole.CITIZEN,
    residentStatus: "Permanent Resident",
    city: "Metro Central (Ward 4)",
    profilePhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    civicPoints: 420,
    civicLevel: "Community Champion",
    trustScore: 94,
    memberSince: "2025-03-10",
    reportsSubmitted: 18,
    reportsValidated: 14,
    issuesResolved: 11,
    estimatedImpacted: 8400,
    impactLevel: "HIGH",
  },
  {
    id: "usr_visitor_01",
    name: "Elena Rostova",
    email: "elena.r@tourist-globe.org",
    phone: "+44 7700 900142",
    role: UserRole.VISITOR,
    residentStatus: "Tourist / Visitor",
    country: "United Kingdom",
    city: "Visiting Metro Central",
    visitDuration: "14 Days (Check-in: Aug 18)",
    profilePhoto: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    civicPoints: 80,
    civicLevel: "Civic Contributor",
    trustScore: 98,
    memberSince: "2026-08-18",
    reportsSubmitted: 3,
    reportsValidated: 2,
    issuesResolved: 2,
    estimatedImpacted: 1200,
    impactLevel: "MEDIUM",
  },
];

export const initialMockCases = [
  {
    id: "case-rd-901",
    complaint_id: "CMP-2026-8821",
    userId: "usr_resident_01",
    citizen_name: "Marcus Vance",
    raw_text: "Major deep pothole in the middle of 5th Avenue intersection right in front of Lincoln High School. Cars are swerving into oncoming traffic to avoid damaging wheels.",
    category: Category.ROADS,
    sub_category: "Pothole / Road Surface Damage",
    summary: "High-risk pothole located in active school zone creating severe vehicular collision hazard.",
    confidence: 0.96,
    department: "Roads & Infrastructure",
    priority: Priority.CRITICAL,
    validatedSeverity: Priority.CRITICAL,
    civicPointsAwarded: 50,
    pointsBreakdown: {
      basePoints: 30,
      evidenceBonus: 5,
      impactBonus: 10,
      resolutionBonus: 5,
      reason: "+30 High Impact +10 Reach (2,500 people) +5 Photo Proof +5 Resolution",
    },
    priority_breakdown: {
      score: 92,
      level: Priority.CRITICAL,
      factors: [
        { factor: "School Zone Proximity", points: 35, description: "Within 50m of Lincoln High School during active hours" },
        { factor: "Traffic Collision Risk", points: 30, description: "Causes vehicles to veer into opposite lane" },
        { factor: "Multi-Citizen Reports", points: 15, description: "3 duplicate reports received in last 2 hours" },
        { factor: "Road Classification", points: 12, description: "Major arterial collector road (5th Ave)" }
      ]
    },
    status: Status.IN_PROGRESS,
    status_history: [
      {
        status: Status.SUBMITTED,
        message: "Citizen complaint registered via mobile portal. NLP parsing initiated.",
        timestamp: "2026-08-21T08:15:00Z",
        updated_by: "AI IntakeAgent",
      },
      {
        status: Status.UNDER_REVIEW,
        message: "AI Agent assigned category 'Roads' with 96% confidence and flagged Critical priority due to school zone proximity.",
        timestamp: "2026-08-21T08:15:45Z",
        updated_by: "AI PrioritizationAgent",
      },
      {
        status: Status.ASSIGNED,
        message: "Officially validated by Department Dispatcher. +50 Civic Contribution Points credited to citizen.",
        timestamp: "2026-08-21T08:20:00Z",
        updated_by: "Officer Sarah Chen (Roads Dept)",
      },
      {
        status: Status.IN_PROGRESS,
        message: "Asphalt patch truck dispatched and crew currently setting up traffic safety cones.",
        timestamp: "2026-08-21T09:30:00Z",
        updated_by: "Officer J. Miller (Roads Dept)",
      }
    ],
    citizen_count: 4,
    location: {
      lat: 37.7749,
      lng: -122.4194,
      address: "850 5th Avenue, near Lincoln High School",
      ward: "Ward 4 - Central West",
      zone: "Zone B",
    },
    attachments: [
      { name: "pothole_crater_depth.jpg", size: "2.4 MB", url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80" },
    ],
    image_tags: ["pothole", "asphalt_crack", "traffic_hazard", "high_depth"],
    sla_deadline: "2026-08-21T14:15:00Z",
    created_at: "2026-08-21T08:15:00Z",
    updated_at: "2026-08-21T09:30:00Z",
  },
  {
    id: "case-wt-442",
    complaint_id: "CMP-2026-7419",
    userId: "usr_resident_01",
    citizen_name: "Marcus Vance",
    raw_text: "Clean drinking water main pipe burst under the sidewalk on Oakridge Lane. Water is gushing onto the road and pressure in surrounding homes has dropped to zero.",
    category: Category.WATER,
    sub_category: "Main Pipe Rupture / Flooding",
    summary: "Drinking water main pipe rupture causing residential pressure loss and surface flooding.",
    confidence: 0.98,
    department: "Water & Sewage Board",
    priority: Priority.CRITICAL,
    validatedSeverity: Priority.CRITICAL,
    civicPointsAwarded: 50,
    pointsBreakdown: {
      basePoints: 30,
      evidenceBonus: 5,
      impactBonus: 10,
      resolutionBonus: 5,
      reason: "+30 Utility disruption +10 Reach (120 households) +5 Photo proof +5 Verified",
    },
    priority_breakdown: {
      score: 95,
      level: Priority.CRITICAL,
      factors: [
        { factor: "Utility Service Outage", points: 40, description: "Affects drinking water supply to ~120 households" },
        { factor: "Infrastructure Damage", points: 30, description: "Risk of sidewalk collapse and asphalt undermining" },
        { factor: "Resource Loss", points: 25, description: "High volume treated potable water wastage" }
      ]
    },
    status: Status.ASSIGNED,
    status_history: [
      {
        status: Status.SUBMITTED,
        message: "Emergency complaint logged with high urgency keywords.",
        timestamp: "2026-08-21T09:00:00Z",
        updated_by: "AI IntakeAgent",
      },
      {
        status: Status.UNDER_REVIEW,
        message: "AI classified as Water Supply Main failure. Emergency SLA invoked.",
        timestamp: "2026-08-21T09:01:10Z",
        updated_by: "AI PrioritizationAgent",
      },
      {
        status: Status.ASSIGNED,
        message: "Emergency valve shutdown team dispatched to isolate sector valve. +50 Civic Points awarded.",
        timestamp: "2026-08-21T09:10:00Z",
        updated_by: "Officer D. Wu (Water Board)",
      }
    ],
    citizen_count: 7,
    location: {
      lat: 37.7833,
      lng: -122.4167,
      address: "1420 Oakridge Lane, Block 12",
      ward: "Ward 2 - North Heights",
      zone: "Zone A",
    },
    attachments: [
      { name: "water_pipe_leak.jpg", size: "1.8 MB", url: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=600&auto=format&fit=crop&q=80" },
    ],
    image_tags: ["water_flood", "burst_pipe", "sidewalk_damage"],
    sla_deadline: "2026-08-21T15:00:00Z",
    created_at: "2026-08-21T09:00:00Z",
    updated_at: "2026-08-21T09:10:00Z",
  },
  {
    id: "case-wm-105",
    complaint_id: "CMP-2026-5510",
    userId: "usr_visitor_01",
    citizen_name: "Elena Rostova",
    raw_text: "Commercial garbage bins overflowing onto pedestrian walkway outside Greenleaf Market for 3 days. Strong foul odor and attracting stray animals.",
    category: Category.WASTE,
    sub_category: "Illegal Waste Dump / Overflow",
    summary: "Solid waste overflow on commercial pedestrian walkway causing hygiene and odor issue.",
    confidence: 0.94,
    department: "Solid Waste Management",
    priority: Priority.HIGH,
    validatedSeverity: Priority.HIGH,
    civicPointsAwarded: 30,
    status: Status.IN_PROGRESS,
    status_history: [
      {
        status: Status.SUBMITTED,
        message: "Visitor complaint submitted with photo proof.",
        timestamp: "2026-08-20T14:30:00Z",
        updated_by: "AI IntakeAgent",
      },
      {
        status: Status.ASSIGNED,
        message: "Assigned to Commercial Waste Route #7 compaction truck. +30 Visitor Points credited.",
        timestamp: "2026-08-20T16:00:00Z",
        updated_by: "RoutingAgent",
      },
      {
        status: Status.IN_PROGRESS,
        message: "Sanitation team on site for bulk collection and sanitization sweep.",
        timestamp: "2026-08-21T08:00:00Z",
        updated_by: "Officer S. Chen",
      }
    ],
    citizen_count: 2,
    location: {
      lat: 37.7650,
      lng: -122.4200,
      address: "310 Market Square, outside Greenleaf",
      ward: "Ward 3 - Downtown Core",
      zone: "Zone A",
    },
    attachments: [
      { name: "waste_bins_overflow.jpg", size: "3.1 MB", url: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80" },
    ],
    image_tags: ["garbage_pile", "overflow_dumpster", "sidewalk_obstruction"],
    sla_deadline: "2026-08-21T14:30:00Z",
    created_at: "2026-08-20T14:30:00Z",
    updated_at: "2026-08-21T08:00:00Z",
  },
  {
    id: "case-sl-303",
    complaint_id: "CMP-2026-3392",
    userId: "usr_resident_01",
    citizen_name: "Marcus Vance",
    raw_text: "Three consecutive streetlights are out along Elm Street pedestrian corridor. It is pitch dark at night and students walk home through here.",
    category: Category.STREETLIGHT,
    sub_category: "Streetlight Outage (Multi-pole)",
    summary: "Dark corridor hazard: 3 adjacent streetlights defective on primary student walkway.",
    confidence: 0.95,
    department: "Street Lighting & Electrical",
    priority: Priority.HIGH,
    validatedSeverity: Priority.HIGH,
    civicPointsAwarded: 30,
    status: Status.ESCALATED,
    status_history: [
      {
        status: Status.SUBMITTED,
        message: "Citizen complaint registered.",
        timestamp: "2026-08-19T20:00:00Z",
        updated_by: "AI IntakeAgent",
      },
      {
        status: Status.ASSIGNED,
        message: "Assigned to Electrical Maintenance Team 2.",
        timestamp: "2026-08-20T08:00:00Z",
        updated_by: "RoutingAgent",
      },
      {
        status: Status.ESCALATED,
        message: "SLA (24h) threshold breached. Case automatically escalated to Electrical Superintendent.",
        timestamp: "2026-08-21T08:05:00Z",
        updated_by: "EscalationAgent",
      }
    ],
    citizen_count: 5,
    location: {
      lat: 37.7600,
      lng: -122.4350,
      address: "Poles #SL-401, 402, 403 on Elm St",
      ward: "Ward 5 - University District",
      zone: "Zone C",
    },
    attachments: [
      { name: "dark_street.jpg", size: "1.2 MB", url: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80" },
    ],
    image_tags: ["streetlight_defect", "night_darkness"],
    sla_deadline: "2026-08-20T20:00:00Z",
    created_at: "2026-08-19T20:00:00Z",
    updated_at: "2026-08-21T08:05:00Z",
  },
  {
    id: "case-oth-112",
    complaint_id: "CMP-2026-0045",
    userId: "usr_resident_01",
    citizen_name: "Marcus Vance",
    raw_text: "Broken public drinking-water dispenser in city square leaking continuously into flowerbeds.",
    category: Category.OTHER,
    custom_category_specification: "Broken public drinking-water dispenser",
    sub_category: "Public Amenity Malfunction",
    summary: "Public park water dispenser valve failure causing continuous drainage overflow.",
    confidence: 0.93,
    department: "Water & Sewage Board",
    priority: Priority.LOW,
    validatedSeverity: Priority.LOW,
    civicPointsAwarded: 20,
    status: Status.RESOLVED,
    status_history: [
      {
        status: Status.SUBMITTED,
        message: "Citizen specified custom issue 'Broken public drinking-water dispenser'. AI auto-routed to Water & Public Amenities.",
        timestamp: "2026-08-18T10:00:00Z",
        updated_by: "AI IntakeAgent",
      },
      {
        status: Status.ASSIGNED,
        message: "Assigned for park plumbing maintenance. +20 Civic Points awarded.",
        timestamp: "2026-08-18T14:00:00Z",
        updated_by: "Officer S. Chen",
      },
      {
        status: Status.RESOLVED,
        message: "Dispenser valve replaced and sealed. Tested successfully.",
        timestamp: "2026-08-20T11:30:00Z",
        updated_by: "Maintenance Crew #3",
      }
    ],
    citizen_count: 2,
    location: {
      lat: 37.7500,
      lng: -122.4400,
      address: "420 Sunset Blvd, Central Park East",
      ward: "Ward 1 - South Valley",
      zone: "Zone C",
    },
    attachments: [],
    image_tags: ["water_dispenser", "park_amenity"],
    sla_deadline: "2026-08-21T10:00:00Z",
    created_at: "2026-08-18T10:00:00Z",
    updated_at: "2026-08-20T11:30:00Z",
  }
];

export const initialClaimedRewards = [
  {
    id: "clm-001",
    userId: "usr_resident_01",
    rewardId: "rew-res-01",
    title: "Digital Civic Contributor Badge",
    pointsUsed: 50,
    claimedAt: "2026-07-12T14:00:00Z",
    voucherCode: "CIVIC-BADGE-7741",
    status: "ACTIVE",
    expiryDate: "2027-07-12",
  },
  {
    id: "clm-002",
    userId: "usr_resident_01",
    rewardId: "rew-res-02",
    title: "Priority Community Program Pass",
    pointsUsed: 150,
    claimedAt: "2026-08-01T10:30:00Z",
    voucherCode: "PASS-COMMUNITY-9921",
    status: "ACTIVE",
    expiryDate: "2026-12-31",
  },
  {
    id: "clm-003",
    userId: "usr_visitor_01",
    rewardId: "rew-vis-01",
    title: "Civic Tourist Welcome Badge",
    pointsUsed: 20,
    claimedAt: "2026-08-19T09:00:00Z",
    voucherCode: "TOURIST-PERK-3341",
    status: "ACTIVE",
    expiryDate: "2026-09-18",
  }
];

export const mockDepartmentStats = {
  "roads": {
    department: "Roads & Infrastructure",
    total_cases: 42,
    open_cases: 12,
    in_progress: 18,
    resolved: 10,
    escalated: 2,
    avg_resolution_hours: 14.5,
  },
  "water": {
    department: "Water & Sewage Board",
    total_cases: 28,
    open_cases: 6,
    in_progress: 14,
    resolved: 7,
    escalated: 1,
    avg_resolution_hours: 8.2,
  },
  "waste": {
    department: "Solid Waste Management",
    total_cases: 35,
    open_cases: 8,
    in_progress: 12,
    resolved: 14,
    escalated: 1,
    avg_resolution_hours: 11.0,
  },
  "streetlight": {
    department: "Street Lighting & Electrical",
    total_cases: 22,
    open_cases: 5,
    in_progress: 8,
    resolved: 7,
    escalated: 2,
    avg_resolution_hours: 19.4,
  },
  "drainage": {
    department: "Stormwater & Drainage",
    total_cases: 19,
    open_cases: 7,
    in_progress: 6,
    resolved: 5,
    escalated: 1,
    avg_resolution_hours: 16.0,
  },
  "public_safety": {
    department: "Public Safety & Hazards",
    total_cases: 15,
    open_cases: 3,
    in_progress: 7,
    resolved: 4,
    escalated: 1,
    avg_resolution_hours: 4.8,
  },
};

export const mockHotspots = [
  {
    ward: "Ward 4 - Central West",
    complaint_count: 38,
    primary_category: Category.ROADS,
    risk_level: "HIGH",
    avg_sla_hours: 12.4,
    top_issue: "Potholes along 5th Ave and Transit Corridor",
  },
  {
    ward: "Ward 2 - North Heights",
    complaint_count: 29,
    primary_category: Category.WATER,
    risk_level: "MEDIUM",
    avg_sla_hours: 9.1,
    top_issue: "Aging main pipe pressure fluctuations",
  },
  {
    ward: "Ward 5 - University District",
    complaint_count: 24,
    primary_category: Category.STREETLIGHT,
    risk_level: "HIGH",
    avg_sla_hours: 18.0,
    top_issue: "Electrical circuit failures in night corridors",
  },
  {
    ward: "Ward 3 - Downtown Core",
    complaint_count: 31,
    primary_category: Category.WASTE,
    risk_level: "MEDIUM",
    avg_sla_hours: 10.5,
    top_issue: "Commercial waste bin capacity overages",
  },
];
